#!/bin/bash

echo "🔧 Adding new files to Xcode project..."
echo ""
echo "Files to add:"
echo "  • AppDelegate.swift"
echo "  • ZoomState.swift"
echo "  • Components/ (entire directory)"
echo "  • Extensions/"
echo "  • Helpers/"
echo "  • Models/"
echo "  • Styles/"
echo "  • Views/Playlists/"
echo "  • Views/Sheets/"
echo "  • Views/PluginDetailView.swift"
echo "  • Views/PrintablePluginTextView.swift"
echo ""
echo "Opening Xcode..."
open PluginReporter.xcodeproj

sleep 2

echo ""
echo "📋 INSTRUCTIONS:"
echo "1. In Xcode, right-click 'PluginReporter' in the Navigator"
echo "2. Select 'Add Files to \"PluginReporter\"...'"
echo "3. Hold Cmd and click to select all these:"
echo "   - AppDelegate.swift"
echo "   - ZoomState.swift"
echo "   - Components folder"
echo "   - Extensions folder"
echo "   - Helpers folder"
echo "   - Models folder"
echo "   - Styles folder"
echo "   - Views folder (will add subdirectories)"
echo "4. In the dialog:"
echo "   ✅ Check 'Create groups'"
echo "   ✅ Check target 'PR MAC'"
echo "   ⬜ Uncheck 'Copy items if needed'"
echo "5. Click 'Add'"
echo "6. Clean Build Folder (Cmd+Shift+K)"
echo "7. Build (Cmd+B)"
echo ""
echo "✅ All build errors should be resolved!"
